name: Check out
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: 'Dr-Nois/MyPrac' # The repository I'm using 
          ref: 'master' # Current version
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: 'false'
          path: 'my-folder' # This should be a new folder
          clean: 'true'
          fetch-depth: '0' # This is always set as 1, I think 0 is OK.
          fetch-tags: 'true'
          submodules: 'recursive' # This can be 'true', 'false' or 'recursive'

- name: Notify Slack
  uses: rtCamp/action-slack-notify@v2
  env:
    SLACK_WEBHOOK: ${{ https://app.slack.com/client/T062D42K1S9/C062FUG363V?geocode=zh-sg }}
  with:
    status: ${{ job.status }}
    text: 'Vulnerabilities found in the code base. Please check the attached report.'
    author_name: 'GitHub Actions'
    author_link: 'https://github.com/features/actions'
    author_icon: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png'
    title: 'Vulnerability Report'
    fields: 'Attachment'
    color: 'danger'
    actions: 'attachment'

- name: Run Trivy vulnerability scanner in fs mode
  uses: aquasecurity/trivy-action@master
  with:
    scan-type: 'fs'
    scan-ref: '.'
    trivy-config: trivy.yaml

- name: Notify about vulnerabilities
  uses: rtCamp/action-slack-notify@v2
  if: ${{ always() }}
  with:
    status: 'Vulnerabilities Found'
    message: 'Vulnerabilities were found in the code base. Please review the attached report.'
    fields: |
      [
        {"title": "Report", "value": "attachment://trivy-report.json", "short": false}
      ]
  env:
    SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  with:
    channel: 'your_slack_channel_name'
    attachment: 'trivy-report.json'
