name: GcmCICD
on:
  push:
    branches:
      - 'v[0-9]+.[0-9]+'


jobs:
  trivy-scan-code:
    runs-on: ubuntu-latest
    name: Scan
    if: ${{ !startsWith(github.event.head_commit.message, '#NORUN') }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@master

        # One of my friends sugested me to use the txt instead of table to show the output.
      - name: Run Trivy vulnerability scanner in repo mode
        id: scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          output: 'trivy-report.txt'
          exit-code: "1"
          severity: CRITICAL 
          # Leanred from "https://github.com/marketplace/actions/aqua-security-trivy" 


      - name: Scan failed send notification to slack
        if: ${{ failure() && steps.scan.conclusion == 'failure' }}
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: ${{ secret.MY_SECRET_CHANNEL }}
          SLACK_COLOR: ${{ job.status }} 
          SLACK_MESSAGE: 'Failed trivy scan,see uploaded report'
          SLACK_TITLE: Scan failed - Guo Chenming
          SLACK_USERNAME: DipSA_CICD
          SLACK_WEBHOOK: ${{ secrets.MY_SECRET_SC }}


      - name: slack send trivy scan reports
        if: ${{ failure() && steps.scan.conclusion == 'failure' }}
        uses: MeilCli/slack-upload-file@master
        with:
          slack_token: ${{ secrets.MY_SECRET_BT }}
          channel_id: ${{ secrets.MY_SECRET_CHANNEL }}
          file_path: 'trivy-report.txt'
          initial_comment: 'Scan report by Guo Chenming'


