name: Check out
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: 'owner/repository-name' # 替换为要检出的存储库的名称和所有者
          ref: 'master' # 替换为要检出的分支、标签或 SHA
          token: ${{ secrets.GITHUB_TOKEN }} # 使用 GitHub 提供的令牌变量
          persist-credentials: 'false' # 根据需要设置为 'true' 或 'false'
          path: 'my-folder' # 替换为要将存储库检出到的特定路径
          clean: 'true' # 根据需要设置为 'true' 或 'false'
          fetch-depth: '0' # 根据需要设置要获取的提交数，0 表示获取所有历史记录
          fetch-tags: 'true' # 根据需要设置为 'true' 或 'false'
          submodules: 'recursive' # 根据需要设置为 'true'、'false' 或 'recursive'
